"""Create omni theme directories from palettes and wallpapers.

Shared by the ``omni theme create`` CLI command and the GUI: both need
to persist an extracted palette as a loadable theme directory::

    themes/<id>/
    ├── theme.toml      # [theme] metadata + [wallpaper]
    ├── colors.toml     # the full semantic role set
    ├── surfaces.toml   # [popups] / [controls] derived from the palette
    └── wallpapers/<name>

Note on write policy: :func:`core.filesystem.atomic_write` restricts
destinations to the XDG roots because those are *user state*. Theme
source directories are authoring material that may live inside a repo
checkout (outside any XDG root), so this module performs the same
temp-file + ``os.replace`` atomic install without the XDG containment
check, into a directory it creates itself.
"""

from __future__ import annotations

import os
import re
import tempfile
from pathlib import Path

from core.errors import ThemeError
from core.theme_model import VALID_MODES
from core.wallpaper_extractor import PALETTE_ROLES

__all__ = ["create_theme_dir", "slugify"]

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def slugify(name: str) -> str:
    """``"Sunset Beach!"`` → ``"sunset-beach"``; ThemeError when empty."""
    slug = _SLUG_RE.sub("-", name.strip().lower()).strip("-")
    if not slug:
        raise ThemeError(f"theme name {name!r} produces an empty id")
    return slug


def _atomic_install(target: Path, payload: bytes | str) -> Path:
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = "wb" if isinstance(payload, bytes) else "w"
    encoding = None if isinstance(payload, bytes) else "utf-8"
    fd, tmp_name = tempfile.mkstemp(dir=target.parent, prefix=f".{target.name}.", suffix=".tmp")
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, mode, encoding=encoding) as fh:
            fh.write(payload)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp_path, target)
    except BaseException:
        tmp_path.unlink(missing_ok=True)
        raise
    return target


def _theme_toml(name: str, theme_id: str, mode: str, wallpaper_name: str | None) -> str:
    lines = [
        f'# Theme "{name}" — generated by omni (wallpaper extraction).',
        "",
        "[theme]",
        f'name = "{name}"',
        f'id = "{theme_id}"',
        "version = 1",
        f'mode = "{mode}"',
        "",
    ]
    if wallpaper_name:
        lines += ["[wallpaper]", f'default = "wallpapers/{wallpaper_name}"', ""]
    return "\n".join(lines)


def _colors_toml(colors: dict[str, str]) -> str:
    lines = [
        "# Generated palette (semantic roles → '#RRGGBB').",
        "# See themes/default/colors.toml for role documentation.",
        "",
    ]
    width = max(len(role) for role in colors)
    for role in PALETTE_ROLES:
        if role in colors:
            lines.append(f"{role:<{width}} = \"{colors[role]}\"")
    lines.append("")
    return "\n".join(lines)


def _surfaces_toml(colors: dict[str, str]) -> str:
    accent = colors.get("accent", "#4f9eea")
    accent_secondary = colors.get("accent_secondary", "#8f6caf")
    popups_bg = colors.get("lighter_background", "#1e222b")
    controls_border = colors.get("dark_foreground", "#3a4150")
    return "\n".join(
        [
            "# UI surface roles derived from the extracted palette.",
            "",
            "[popups]",
            f'background    = "{popups_bg}"',
            f'border        = "{accent}"',
            "border-width  = 2",
            "",
            "[controls]",
            f'normal-border = "{controls_border}"',
            f'focus-border  = "rgba({accent.lstrip("#")}ee) '
            f'rgba({accent_secondary.lstrip("#")}ee) 45deg"',
            "",
        ]
    )


def create_theme_dir(
    root: str | Path,
    *,
    name: str,
    colors: dict[str, str],
    mode: str = "dark",
    wallpaper: str | Path | None = None,
    force: bool = False,
) -> Path:
    """Write a new theme directory under *root* and return its path.

    *colors* must provide at least the roles the templates render; a
    wallpaper image, when given, is copied into ``wallpapers/`` and
    declared as the theme default. Refuses to overwrite an existing
    theme unless *force* is set.
    """
    if mode not in VALID_MODES:
        raise ThemeError(f"mode must be one of {'/'.join(VALID_MODES)}, got {mode!r}")
    missing = [role for role in PALETTE_ROLES if role not in colors]
    if missing:
        raise ThemeError(f"palette is missing roles: {', '.join(missing[:8])}"
                         + (f" (+{len(missing) - 8} more)" if len(missing) > 8 else ""))

    theme_id = slugify(name)
    theme_dir = Path(root) / theme_id
    if theme_dir.exists():
        if not force:
            raise ThemeError(
                f"theme directory already exists: {theme_dir} (use force to overwrite)"
            )
    theme_dir.mkdir(parents=True, exist_ok=force)

    wallpaper_name: str | None = None
    if wallpaper is not None:
        source = Path(wallpaper).expanduser()
        if not source.is_file():
            raise ThemeError(f"wallpaper image not found: {source}")
        wallpaper_name = source.name
        destination = theme_dir / "wallpapers" / wallpaper_name
        destination.parent.mkdir(parents=True, exist_ok=True)
        if source.resolve() != destination.resolve():
            _atomic_install(destination, source.read_bytes())

    _atomic_install(theme_dir / "theme.toml",
                        _theme_toml(name, theme_id, mode, wallpaper_name))
    _atomic_install(theme_dir / "colors.toml", _colors_toml(colors))
    _atomic_install(theme_dir / "surfaces.toml", _surfaces_toml(colors))
    return theme_dir
